package model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_category", "id", Category.class);
		// Composite Primary Key order: deleted,id
		arp.addMapping("t_reply", "deleted,id", Reply.class);
		arp.addMapping("t_topic", "id", Topic.class);
		arp.addMapping("t_user", "id", User.class);
	}
}

